development:
  adapter: postgresql
  encoding: unicode
  database: depot_development
  pool: 5
  timeout: 5000
  username: orlovic
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: depot_test
  pool: 5
  timeout: 5000
  username: orlovic
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: dc2fdk9bj55p9l
  pool: 5
  username: ptnibwiskaodvl
  password: GD27nFqeiFGnJehCkd-3r8ARrf
  host: ec2-54-243-212-162.compute-1.amazonaws.com
  port: 5432
